### PR TITLE
fix(AAE-1012): Unreleased Liquibase lock prevents the application start up

### LINKED ISSUE #3595: Unreleased Liquibase lock prevents the application start up
It's happening randomly probably when a migration step is applied. The application fails to start with the following error:

```
2019-11-28 09:18:19.224 ERROR 1 --- [ main] o.s.b.web.embedded.tomcat.TomcatStarter : Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'commonSecurityAutoConfiguration': Unsatisfied dependency expressed through method 'setContentNegotationStrategy' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'alfrescoWebAutoConfiguration' defined in URL [jar:file:/opt/app.jar!/BOOT-INF/lib/activiti-cloud-services-dbp-rest-7.1.94.jar!/org/activiti/cloud/alfresco/config/AlfrescoWebAutoConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pageableResolver' defined in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.web.HateoasPageableHandlerMethodArgumentResolver]: Factory method 'pageableResolver' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sortResolver' defined in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.web.SortHandlerMethodArgumentResolver]: Factory method 'sortResolver' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repositoryRestConfiguration' defined in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.rest.core.config.RepositoryRestConfiguration]: Factory method 'repositoryRestConfiguration' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repositories' defined in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.repository.support.Repositories]: Factory method 'repositories' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'modelJpaRepository': Cannot create inner bean '(inner bean)#59e43e8c' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#59e43e8c': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LockException: Could not acquire change log lock. Currently locked by staging-full-chart-activiti-cloud-modeling-f4499bf5c-9vfpd (10.52.50.4) since 11/26/19, 11:40 AM
2019-11-28 09:18:19.298 INFO 1 --- [ main] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock_org_service
2019-11-28 09:18:19.300 INFO 1 --- [ main] liquibase.executor.jvm.JdbcExecutor : SELECT COUNT(*) FROM public.databasechangeloglock_org_service
2019-11-28 09:18:19.301 INFO 1 --- [ main] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock_org_service WHERE ID=1
2019-11-28 09:18:19.302 INFO 1 --- [ main] l.lockservice.StandardLockService : Waiting for changelog lock....
2019-11-28 09:18:29.303 INFO 1 --- [ main] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock_org_service WHERE ID=1
2019-11-28 09:18:29.305 INFO 1 --- [ main] l.lockservice.StandardLockService : Waiting for changelog lock....
2019-11-28 09:18:39.306 INFO 1 --- [ main] liquibase.executor.jvm.JdbcExecutor : SELECT LOCKED FROM public.databasechangeloglock_org_service WHERE ID=1

```
**What is probably happening:**

- Spring boot app starts and Liquibase add a lock to update db schema
- The update takes too long and k8s kills the application (liveness/readiness prob)
- The lock is never released and the application is not able to start anymore

Possible solutions:

- Increase timeout in the start up: it's hard to now how long the migration will take
- Perform the migration inside a initContainer
- Provide migration as an external tool

### PR DESCRIPTION
**Pull request by igdianov**
This PR provides refactoring of Liquibase in Query and Audit services:

- [x] Extract Liquibase resources into separate module inside activiti-cloud repository, so that they can be used as dependencies.
- [x] Include and use Liqubase dependency module within service starter modules
- [x] Add reusable `activiti-cloud-service-common-liquibase` module

Fixes https://alfresco.atlassian.net/browse/AAE-1012
Fixes https://github.com/Activiti/Activiti/issues/3595

### CODE REVIEW

File: activiti-cloud-audit-service/activiti-cloud-services-audit-liquibase/src/main/java/org/activiti/cloud/services/audit/liquibase/ActivitiCloudAuditLiquibaseAutoConfiguration.java [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+        liquibase.setDropFirst(properties.isDropFirst());
+        liquibase.setShouldRun(properties.isEnabled());
+        liquibase.setLabels(properties.getLabels());
+        liquibase.setChangeLogParameters(properties.getParameters());
+        liquibase.setRollbackFile(properties.getRollbackFile());
+        liquibase.setDatabaseChangeLogTable(properties.getDatabaseChangeLogTable());
+        liquibase.setDatabaseChangeLogLockTable(properties.getDatabaseChangeLogLockTable());
+        liquibase.setTestRollbackOnUpdate(properties.isTestRollbackOnUpdate());
+        return liquibase;
+    }
```
Comment (erdemedeiros) [inline activiti-cloud-audit-service/activiti-cloud-services-audit-liquibase/src/main/java/org/activiti/cloud/services/audit/liquibase/ActivitiCloudAuditLiquibaseAutoConfiguration.java]: We should consider extracting this block in a shared place, as we have exactly the same code for `audit`, `query`, and `modeling`.

**Review by erdemedeiros — CHANGES_REQUESTED** [review]

File: activiti-cloud-audit-service/activiti-cloud-services-audit-liquibase/src/main/java/org/activiti/cloud/services/audit/liquibase/ActivitiCloudAuditLiquibaseAutoConfiguration.java (hunk 1 above)
Comment (igdianov) [reply activiti-cloud-audit-service/activiti-cloud-services-audit-liquibase/src/main/java/org/activiti/cloud/services/audit/liquibase/ActivitiCloudAuditLiquibaseAutoConfiguration.java]: Fixed in 6ea8111da574263878d73a62104037772f0be3f9

**Review by erdemedeiros — APPROVED** [review]
LTGM
