### PR TITLE
Process validation missing common invalid conditions

### LINKED ISSUE #3475: Process validation missing common invalid conditions
Process validation does not detect some common invalid conditions such as:
- a missing sequence flow between activities
- sequence flows routed into a Start Event

### LINKED ISSUE #3482: [Modeling app] Enhance basic process validation
**Summary**
In the modeling application you can save and validate a process that doesn't have an end event. Furthermore, there is no check that determine if all the branches have a connection to an end event

**Steps to reproduce the problem:**
1. In the modeling application create a new process and don´t place an end event into it
2. Validate and try to save the process

**Expected behavior:**
An error should be reported

**Current behavior:**
You can validate and save the form without any error displayed

### PR DESCRIPTION
**Pull request by amohammedalfresco**
Fixes [Activiti/issues#3475](https://github.com/Activiti/Activiti/issues/3475)
Fixes [Activiti/issues#3482](https://github.com/Activiti/Activiti/issues/3482)

### CODE REVIEW

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+
+    private List<ModelValidationError> validateTaskFlow(FlowElement flowElement) {
+
+        List<ModelValidationError> errors = new ArrayList<>();
+        if (!(flowElement instanceof FlowNode)) {
+            return errors;
+        }
+
+        FlowNode flowNode = (FlowNode) flowElement;
+        if (flowNode instanceof StartEvent) {
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: I'd change a little bit the structure of the code to the apply strategy pattern, having a different strategy for flow-node type: we can isolate the validators to make them simpler so easier to test as well:
- extract the interface `IncomingOutgoingFlowValidator` or `FlowNodeFlowsValidator` (for a shorter name) with the methods: `List<ModelValidationError> validate (FlowNode flowNode)` and `boolean canValidate(FlowNode flowNode)` 
- create 3 implementations of this interface: `StartEventIncomingOutgoingFlowValidator`, `EndEventIncomingOutgoingFlowValidator` and `IntermerdiateFlowNodeIncomingOutgoingFlowValidator`
- the current class will receive a list of IncomingOutgoingFlowValidator in the constructor and will iterate over them:
```
for (IncomingOutgoingFlowValidator validator: validators) {
	if (valaditor.canValidate(flowNode)){
		errors.addAll(validator.validate(flowNode));
	}
}
```
In this way, you can write unit tests for every individual validator. What do you think?

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+import java.util.ArrayList;
+import java.util.List;
+import java.util.stream.Stream;
+
+/**
+ * Implementation of {@link BpmnModelValidator} for validating Incoming and Outgoing flows
+ */
+public class BpmnModelIncomingOutgoingFlowValidator implements BpmnModelValidator{
+
+    public final String NO_INCOMING_FLOW_PROBLEM = "Task has no incoming flow";
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: I think the message content should be updated to `Intermediate Flow node has no incoming flow` because this is not validating only tasks, but also gateways, intermediate events, sub-processes, etc.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+    public final String NO_INCOMING_FLOW_PROBLEM_DESCRIPTION = "Task has to have an incoming flow";
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: Same here `Intermediate Flow Node` instead of `Task`.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+    public final String NO_OUTGOING_FLOW_PROBLEM = "Task has no outgoing flow";
+    public final String NO_OUTGOING_FLOW_PROBLEM_DESCRIPTION = "Task has to have an outgoing flow";
+    public final String NO_INCOMING_FLOW_PROBLEM_START_EVENT = "Start event should not have incoming flow";
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: I'd rename it to `INCOMING_FLOW_ON_START_EVENT_PROBLEM`, THE `NO` prefix in the current constant name let me think that the problem is that the start event doesn't have an incoming flow.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java [hunk 5]
```diff
@@ -0,0 +1,104 @@
...
+    public final String NO_INCOMING_FLOW_PROBLEM_DESCRIPTION_START_EVENT = "Start event should not have incoming flow";
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: Same here, I'd rename it to `INCOMING_FLOW_ON_START_EVENT_PROBLEM_DESCRIPTION`.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java [hunk 6]
```diff
@@ -0,0 +1,104 @@
...
+    public final String NO_OUTGOING_FLOW_PROBLEM_END_EVENT = "End event should not have outgoing flow";
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: `OUTGOING_FLOW_ON_END_EVENT_PROBLEM`

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java [hunk 7]
```diff
@@ -0,0 +1,104 @@
...
+    public final String NO_OUTGOING_FLOW_PROBLEM_DESCRIPTION_END_EVENT = "End event should not have outgoing flow";
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: OUTGOING_FLOW_ON_END_EVENT_PROBLEM_DESCRIPTION

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java [hunk 8]
```diff
@@ -0,0 +1,104 @@
...
+    public final String TASK_FLOW_VALIDATOR_NAME = "BPMN Task flow validator";
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: `Flow Node flows validator`, as it's not validating only tasks.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java [hunk 9]
```diff
@@ -0,0 +1,104 @@
...
+                    TASK_FLOW_VALIDATOR_NAME));
+            }
+            if (CollectionUtils.isNotEmpty(flowNode.getOutgoingFlows())) {
+                errors.add(createModelValidationError(NO_OUTGOING_FLOW_PROBLEM_END_EVENT,
+                    NO_OUTGOING_FLOW_PROBLEM_DESCRIPTION_END_EVENT,
+                    TASK_FLOW_VALIDATOR_NAME));
+            }
+
+        } else {
+            if (CollectionUtils.isEmpty(flowNode.getIncomingFlows())) {
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: I'm expecting this to cause problems for event sub-processes as they don't have any incoming or outgoing flow. It probably means that we'll need a fourth implementation of the new interface covering event-subprocesses.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelSequenceFlowValidator.java [hunk 10]
```diff
@@ -0,0 +1,67 @@
...
+import java.util.List;
+import java.util.stream.Stream;
+
+/**
+ * Implementation of {@link BpmnModelValidator} for validating Sequence flow when empty source or target references are provided
+ */
+public class BpmnModelSequenceFlowValidator implements BpmnModelValidator {
+
+    public final String NO_SOURCE_REF_PROBLEM_TITLE = "Sequence flow has no source reference";
+    public final String NO_SOURCE_REF_PROBLEM_DESCRIPTION = "Sequence flow has to have an incoming flow";
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelSequenceFlowValidator.java]: The message in the description doesn't match the one for the title. Title talks about `source reference` and description talks about `incoming flow`.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelSequenceFlowValidator.java [hunk 11]
```diff
@@ -0,0 +1,67 @@
...
+    public final String NO_TARGET_REF_PROBLEM_TITLE = "Sequence flow has no target reference";
+    public final String NO_TARGET_REF_PROBLEM_DESCRIPTION = "Sequence flow has to have an outgoing flow";
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelSequenceFlowValidator.java]: Same here, title and description are not aligned.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java [hunk 12]
```diff
@@ -0,0 +1,104 @@
...
+    public final String NO_INCOMING_FLOW_PROBLEM_DESCRIPTION_START_EVENT = "Start event should not have incoming flow";
+    public final String NO_OUTGOING_FLOW_PROBLEM_END_EVENT = "End event should not have outgoing flow";
+    public final String NO_OUTGOING_FLOW_PROBLEM_DESCRIPTION_END_EVENT = "End event should not have outgoing flow";
+    public final String TASK_FLOW_VALIDATOR_NAME = "BPMN Task flow validator";
+
+    @Override
+    public Stream<ModelValidationError> validate(BpmnModel bpmnModel, ValidationContext validationContext) {
+        List<ModelValidationError> errors = new ArrayList<>();
+        getTasks(bpmnModel,
+            FlowElement.class).forEach(flowElement -> {
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: Why not using directly `FlowNode.class` here, as you're validating only flow nodes?

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelValidator.java [hunk 13]
```diff
@@ -31,8 +31,8 @@
     Stream<ModelValidationError> validate(BpmnModel bpmnModel,
                                           ValidationContext validationContext);
 
-    default <T extends Task> Stream<T> getTasks(BpmnModel bpmnModel,
-                                                Class<T> taskType) {
+    default <T extends FlowElement> Stream<T> getTasks(BpmnModel bpmnModel,
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelValidator.java]: Please, rename the method to `getFlowElements`.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java [hunk 14]
```diff
@@ -0,0 +1,104 @@
...
+import org.apache.commons.collections.CollectionUtils;
+
+import java.util.ArrayList;
+import java.util.List;
+import java.util.stream.Stream;
+
+/**
+ * Implementation of {@link BpmnModelValidator} for validating Incoming and Outgoing flows
+ */
+public class BpmnModelIncomingOutgoingFlowValidator implements BpmnModelValidator{
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java:30]: This validator should be instantiated inside [ProcessModelValidatorConfiguration](https://github.com/Activiti/activiti-cloud/blob/develop/activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/ProcessModelValidatorConfiguration.java).

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelSequenceFlowValidator.java [hunk 15]
```diff
@@ -0,0 +1,67 @@
...
+import org.apache.commons.lang3.StringUtils;
+
+import java.util.ArrayList;
+import java.util.List;
+import java.util.stream.Stream;
+
+/**
+ * Implementation of {@link BpmnModelValidator} for validating Sequence flow when empty source or target references are provided
+ */
+public class BpmnModelSequenceFlowValidator implements BpmnModelValidator {
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelSequenceFlowValidator.java:31]: This validator should be instantiated inside [ProcessModelValidatorConfiguration](https://github.com/Activiti/activiti-cloud/blob/develop/activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/ProcessModelValidatorConfiguration.java).

**Review by erdemedeiros — CHANGES_REQUESTED** [review]
Hi @amohammedalfresco, I have some suggestions for renaming and code refactoring that are described below. Let me know if you want to discuss it.
From what I see Integration tests for validation are [here](https://github.com/Activiti/activiti-cloud/blob/develop/activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-rest/src/test/java/org/activiti/cloud/services/modeling/rest/controller/ModelValidationControllerIT.java#L263)

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java (hunk 14 above)
Comment (amohammedalfresco) [reply activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java:30]: Thanks, I just instantiated it in the configuration class.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelSequenceFlowValidator.java (hunk 15 above)
Comment (amohammedalfresco) [reply activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelSequenceFlowValidator.java:31]: Thanks, I just instantiated it in the configuration class.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java (hunk 12 above)
Comment (amohammedalfresco) [reply activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: Sure, I replaced with `FlowNode.class`

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelValidator.java (hunk 13 above)
Comment (amohammedalfresco) [reply activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelValidator.java]: Updated method name, thanks.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java (hunk 5 above)
Comment (amohammedalfresco) [reply activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: Thanks, I renamed the variable.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java (hunk 4 above)
Comment (amohammedalfresco) [reply activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: Thanks, adjusted the name.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java (hunk 3 above)
Comment (amohammedalfresco) [reply activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: Thanks, I adjusted it.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java (hunk 2 above)
Comment (amohammedalfresco) [reply activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: Thanks, I adjusted it.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java (hunk 1 above)
Comment (amohammedalfresco) [reply activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: Thanks @erdemedeiros.  I refactored the code accordingly and split the previous class into smaller classes and their unit tests.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java [hunk 16]
```diff
@@ -0,0 +1,60 @@
...
+        List<ModelValidationError> errors = new ArrayList<>();
+        getFlowElements(bpmnModel,
+            FlowNode.class).forEach(flowNode -> {
+            errors.addAll(validateTaskFlow(flowNode));
+        });
+
+        return errors.stream();
+    }
+
+    private List<ModelValidationError> validateTaskFlow(FlowNode flowNode) {
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: Naming: it should be `FlowNode` instead of `Task` as it's validating any flow node, not only tasks -> `validateFlowNode`.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/IntermediateFlowNodeIncomingOutgoingFlowValidator.java [hunk 17]
```diff
@@ -0,0 +1,57 @@
...
+            errors.add(createModelValidationError(NO_OUTGOING_FLOW_PROBLEM,
+                NO_OUTGOING_FLOW_PROBLEM_DESCRIPTION,
+                INTERMEDIATE_FLOW_VALIDATOR_NAME));
+        }
+        return errors;
+    }
+
+    @Override
+    public boolean canValidate(FlowNode flowNode) {
+        return !(flowNode instanceof StartEvent) && !(flowNode instanceof EndEvent);
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/IntermediateFlowNodeIncomingOutgoingFlowValidator.java]: You also need to exclude event-subprocesses (`EventSubProcess`):
image

The following XML should pass the validation. Please add an integration test for it:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn2:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn2="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="model-d624d23e-1082-4b19-ac5c-3ff60d3e2975" name="event-subprocess" targetNamespace="http://bpmn.io/schema/bpmn" xsi:schemaLocation="http://www.omg.org/spec/BPMN/20100524/MODEL BPMN20.xsd">
  <bpmn2:process id="Process_wB3JXOkJN" name="event-subprocess" isExecutable="true">
    <bpmn2:documentation />
    <bpmn2:startEvent id="Event_1">
      <bpmn2:outgoing>SequenceFlow_0yge099</bpmn2:outgoing>
    </bpmn2:startEvent>
    <bpmn2:task id="Task_0af35yr" name="Main task">
      <bpmn2:incoming>SequenceFlow_0yge099</bpmn2:incoming>
      <bpmn2:outgoing>SequenceFlow_0pv0hhn</bpmn2:outgoing>
    </bpmn2:task>
    <bpmn2:sequenceFlow id="SequenceFlow_0yge099" sourceRef="Event_1" targetRef="Task_0af35yr" />
    <bpmn2:endEvent id="EndEvent_03l0htc">
      <bpmn2:incoming>SequenceFlow_0pv0hhn</bpmn2:incoming>
    </bpmn2:endEvent>
    <bpmn2:sequenceFlow id="SequenceFlow_0pv0hhn" sourceRef="Task_0af35yr" targetRef="EndEvent_03l0htc" />
    <bpmn2:subProcess id="SubProcess_0o8kx5r" triggeredByEvent="true">
      <bpmn2:task id="Task_1lpq4jr" name="Task in subprocess">
        <bpmn2:incoming>SequenceFlow_0ep94tv</bpmn2:incoming>
        <bpmn2:outgoing>SequenceFlow_14eyqa8</bpmn2:outgoing>
      </bpmn2:task>
      <bpmn2:endEvent id="EndEvent_0hxf3ti">
        <bpmn2:incoming>SequenceFlow_14eyqa8</bpmn2:incoming>
      </bpmn2:endEvent>
      <bpmn2:sequenceFlow id="SequenceFlow_0ep94tv" sourceRef="StartEvent_0pmugnv" targetRef="Task_1lpq4jr" />
      <bpmn2:sequenceFlow id="SequenceFlow_14eyqa8" sourceRef="Task_1lpq4jr" targetRef="EndEvent_0hxf3ti" />
      <bpmn2:startEvent id="StartEvent_0pmugnv">
        <bpmn2:outgoing>SequenceFlow_0ep94tv</bpmn2:outgoing>
        <bpmn2:signalEventDefinition id="SignalEventDefinition_0l3yn3v" signalRef="Signal_0p01hxz" />
      </bpmn2:startEvent>
    </bpmn2:subProcess>
  </bpmn2:process>
  <bpmn2:signal id="Signal_0p01hxz" name="go" />
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_wB3JXOkJN">
      <bpmndi:BPMNShape id="_BPMNShape_Event_2" bpmnElement="Event_1">
        <dc:Bounds x="342" y="232" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Task_0af35yr_di" bpmnElement="Task_0af35yr">
        <dc:Bounds x="470" y="210" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="SequenceFlow_0yge099_di" bpmnElement="SequenceFlow_0yge099">
        <di:waypoint x="378" y="250" />
        <di:waypoint x="470" y="250" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="EndEvent_03l0htc_di" bpmnElement="EndEvent_03l0htc">
        <dc:Bounds x="662" y="232" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="SequenceFlow_0pv0hhn_di" bpmnElement="SequenceFlow_0pv0hhn">
        <di:waypoint x="570" y="250" />
        <di:waypoint x="662" y="250" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Task_1lpq4jr_di" bpmnElement="Task_1lpq4jr">
        <dc:Bounds x="475" y="380" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="SequenceFlow_0ep94tv_di" bpmnElement="SequenceFlow_0ep94tv">
        <di:waypoint x="423" y="420" />
        <di:waypoint x="475" y="420" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="EndEvent_0hxf3ti_di" bpmnElement="EndEvent_0hxf3ti">
        <dc:Bounds x="607" y="402" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="SequenceFlow_14eyqa8_di" bpmnElement="SequenceFlow_14eyqa8">
        <di:waypoint x="575" y="420" />
        <di:waypoint x="607" y="420" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="SubProcess_08j2v4j_di" bpmnElement="SubProcess_0o8kx5r" isExpanded="true">
        <dc:Bounds x="345" y="330" width="350" height="200" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="StartEvent_1xhrzpm_di" bpmnElement="StartEvent_0pmugnv">
        <dc:Bounds x="387" y="402" width="36" height="36" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn2:definitions>
```

On the other hand, embedded subprocesses (not triggered via events should have validation) and the following should fail the validation as the embeded sub-process doesn't have any incoming or outgoing flows:

image
```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn2:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn2="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="model-679b467b-f441-48c9-bf9c-69e2c3067aff" name="embeded-sub-process" targetNamespace="http://bpmn.io/schema/bpmn" xsi:schemaLocation="http://www.omg.org/spec/BPMN/20100524/MODEL BPMN20.xsd">
  <bpmn2:process id="Process_plPmux2Yy" name="embeded-sub-process" isExecutable="true">
    <bpmn2:documentation />
    <bpmn2:startEvent id="Event_1">
      <bpmn2:outgoing>SequenceFlow_0imcv9e</bpmn2:outgoing>
    </bpmn2:startEvent>
    <bpmn2:task id="Task_1fnls1d">
      <bpmn2:incoming>SequenceFlow_0imcv9e</bpmn2:incoming>
      <bpmn2:outgoing>SequenceFlow_0y98alj</bpmn2:outgoing>
    </bpmn2:task>
    <bpmn2:sequenceFlow id="SequenceFlow_0imcv9e" sourceRef="Event_1" targetRef="Task_1fnls1d" />
    <bpmn2:endEvent id="EndEvent_0vi8yr7">
      <bpmn2:incoming>SequenceFlow_0y98alj</bpmn2:incoming>
    </bpmn2:endEvent>
    <bpmn2:sequenceFlow id="SequenceFlow_0y98alj" sourceRef="Task_1fnls1d" targetRef="EndEvent_0vi8yr7" />
    <bpmn2:subProcess id="SubProcess_1j83p8h" name="Embedded sub-process">
      <bpmn2:startEvent id="StartEvent_1dhsk7u">
        <bpmn2:outgoing>SequenceFlow_0qqat5x</bpmn2:outgoing>
      </bpmn2:startEvent>
      <bpmn2:task id="Task_0kzyhu8">
        <bpmn2:incoming>SequenceFlow_0qqat5x</bpmn2:incoming>
        <bpmn2:outgoing>SequenceFlow_1wvp9w4</bpmn2:outgoing>
      </bpmn2:task>
      <bpmn2:sequenceFlow id="SequenceFlow_0qqat5x" sourceRef="StartEvent_1dhsk7u" targetRef="Task_0kzyhu8" />
      <bpmn2:endEvent id="EndEvent_1ug8te0">
        <bpmn2:incoming>SequenceFlow_1wvp9w4</bpmn2:incoming>
      </bpmn2:endEvent>
      <bpmn2:sequenceFlow id="SequenceFlow_1wvp9w4" sourceRef="Task_0kzyhu8" targetRef="EndEvent_1ug8te0" />
    </bpmn2:subProcess>
  </bpmn2:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_plPmux2Yy">
      <bpmndi:BPMNShape id="_BPMNShape_Event_2" bpmnElement="Event_1">
        <dc:Bounds x="412" y="222" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Task_1fnls1d_di" bpmnElement="Task_1fnls1d">
        <dc:Bounds x="520" y="200" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="SequenceFlow_0imcv9e_di" bpmnElement="SequenceFlow_0imcv9e">
        <di:waypoint x="448" y="240" />
        <di:waypoint x="520" y="240" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="EndEvent_0vi8yr7_di" bpmnElement="EndEvent_0vi8yr7">
        <dc:Bounds x="662" y="222" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="SequenceFlow_0y98alj_di" bpmnElement="SequenceFlow_0y98alj">
        <di:waypoint x="620" y="240" />
        <di:waypoint x="662" y="240" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="SubProcess_1j83p8h_di" bpmnElement="SubProcess_1j83p8h" isExpanded="true">
        <dc:Bounds x="380" y="330" width="350" height="200" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="StartEvent_1dhsk7u_di" bpmnElement="StartEvent_1dhsk7u">
        <dc:Bounds x="422" y="412" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Task_0kzyhu8_di" bpmnElement="Task_0kzyhu8">
        <dc:Bounds x="500" y="390" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="SequenceFlow_0qqat5x_di" bpmnElement="SequenceFlow_0qqat5x">
        <di:waypoint x="458" y="430" />
        <di:waypoint x="500" y="430" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="EndEvent_1ug8te0_di" bpmnElement="EndEvent_1ug8te0">
        <dc:Bounds x="642" y="412" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="SequenceFlow_1wvp9w4_di" bpmnElement="SequenceFlow_1wvp9w4">
        <di:waypoint x="600" y="430" />
        <di:waypoint x="642" y="430" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn2:definitions>
```

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/test/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelSequenceFlowValidatorTest.java [hunk 18]
```diff
@@ -0,0 +1,69 @@
...
+        bpmnModelSequenceFlowValidator = new BpmnModelSequenceFlowValidator();
+    }
+
+    @Test
+    public void should_returnError_when_noSourceReferenceIsSpecified() {
+        BpmnModel bpmnModel = CreateBpmnModelTestHelper.createOneTaskTestProcess();
+        SequenceFlow sequenceFlow = (SequenceFlow) bpmnModel.getMainProcess().getFlowElement("testSequenceId");
+        sequenceFlow.setSourceRef(null);
+
+        assertThat(bpmnModelSequenceFlowValidator.validate(bpmnModel, validationContext)).extracting("problem")
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/test/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelSequenceFlowValidatorTest.java]: Prefer method reference instead of literal string --> `.extracting(ModelValidationError::getProblem)`.

Same for all the following tests.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/test/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelSequenceFlowValidatorTest.java [hunk 19]
```diff
@@ -0,0 +1,69 @@
...
+        BpmnModel bpmnModel = CreateBpmnModelTestHelper.createOneTaskTestProcess();
+        SequenceFlow sequenceFlow = (SequenceFlow) bpmnModel.getMainProcess().getFlowElement("testSequenceId");
+        sequenceFlow.setTargetRef(null);
+
+        assertThat(bpmnModelSequenceFlowValidator.validate(bpmnModel, validationContext)).extracting("problem")
+            .contains(BpmnModelSequenceFlowValidator.NO_TARGET_REF_PROBLEM);
+    }
+
+    @Test
+    public void should_returnError_when_noSourceAndTargetReferenceAreSpecified() {
```
Comment (erdemedeiros) [inline activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/test/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelSequenceFlowValidatorTest.java]: In my opinion, you don't need this third test: you have already covered separately `source` and `target`, no need to cover them combined as the implementation is handling them independently.

**Review by erdemedeiros — CHANGES_REQUESTED** [review]
Thank you for the fixes. Here are my following remarks:

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java (hunk 16 above)
Comment (amohammedalfresco) [reply activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelIncomingOutgoingFlowValidator.java]: Thanks, I just fixed that.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/test/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelSequenceFlowValidatorTest.java (hunk 18 above)
Comment (amohammedalfresco) [reply activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/test/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelSequenceFlowValidatorTest.java]: Sure.  I fixed this.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/test/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelSequenceFlowValidatorTest.java (hunk 19 above)
Comment (amohammedalfresco) [reply activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/test/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelSequenceFlowValidatorTest.java]: Sure.  I removed this check.

File: activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/IntermediateFlowNodeIncomingOutgoingFlowValidator.java (hunk 17 above)
Comment (amohammedalfresco) [reply activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/IntermediateFlowNodeIncomingOutgoingFlowValidator.java]: Many thanks for the help, I have added these 2 new integration checks accordingly.

**Review by erdemedeiros — APPROVED** [review]

**Review by balsarori — APPROVED** [review]
LGTM, however errors should point to the exact element that contains a validation error. It will be hard to find where the validation error is coming from in large process models. Probably that work can be done on a separate enhancement ticket.

**Comment by erdemedeiros** [comment]
Good catch @balsarori. @amohammedalfresco, could you, please, create another PR to update the error messages to include the id (and possibly the name) of the flow element?
