### PR TITLE
AAE-42735 Fix sorting related processes by type

### LINKED ISSUE #5318: Sorting related processes by type results in 500 error
{
    "code": 500,
    "message": "Could not resolve attribute 'type' of 'org.activiti.cloud.services.query.model.ProcessInstanceEntity'"
}

### PR DESCRIPTION
**Pull request by tom-dal**
Issue link: AAE-42735

### CODE REVIEW

**Review by mavotto — APPROVED** [review]

**Review by jesty — CHANGES_REQUESTED** [review]
Please create a new column

File: activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/ProcessInstanceEntity.java [hunk 1]
```diff
@@ -245,6 +246,15 @@ public class ProcessInstanceEntity extends ActivitiEntityMetadata implements Que
 
     private String linkedProcessInstanceType;
 
+    @Formula(
+        "CASE " +
+        "WHEN parent_id IS NULL OR parent_id = id THEN 'main-process' " +
+        "WHEN linked_process_instance_type IS NOT NULL THEN linked_process_instance_type " +
+        "WHEN parent_id IS NOT NULL AND parent_id != id THEN 'call-activity' " +
```
Comment (jesty) [inline activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/ProcessInstanceEntity.java]: Please put condition at line 253 as first and then use main-process as default codition.

**Review by jesty — APPROVED** [review]
LGTM

**Review by mavotto — APPROVED** [review]
