### PR TITLE
Fix execute command PropagateCloudBpmnErrorCmd

### LINKED ISSUE #4305: Fix the status update of a service task when an error occurs
When an error occurs, the event update is not sent during a service task and the status is not changed to ERROR.

### PR DESCRIPTION
**Pull request by mavotto**
This PR fixes https://github.com/Activiti/Activiti/issues/4305.

When there is a `CloudBpmnError` the command `new PropagateCloudBpmnErrorCmd(integrationError, execution)` is added, which in this case throws an exception which is caught, then when we re-execute `managementService.executeCommand(CompositeCommand.of(commands.toArray(Command[]::new)));` at the end of the method we still have `PropagateCloudBpmnErrorCmd` in the command list, and then the exception is thrown again, which in this case is not caught, so the event to update the status of the service activity is not sent.

To solve this bug, the command list is cleaned in the catch 
Added unit test for this scenario

### CODE REVIEW

**Review by miguelruizdev — APPROVED** [review]
LGTM

File: activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/channel/ServiceTaskIntegrationErrorEventHandler.java [hunk 1]
```diff
@@ -117,6 +118,12 @@ public void receive(IntegrationError integrationError) {
                             return;
                         } catch (Throwable cause) {
                             LOGGER.error("Error propagating CloudBpmnError: {}", cause.getMessage());
+                            // cleaned the commands list from PropagateCloudBpmnErrorCmd and AggregateIntegrationErrorReceivedClosingEventCmd
```
Comment (jesty) [inline activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/channel/ServiceTaskIntegrationErrorEventHandler.java:121]: instead of a comment, can we extract a method with a proper name? thanks

**Review by jesty — CHANGES_REQUESTED** [review]

File: activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/channel/ServiceTaskIntegrationErrorEventHandler.java [hunk 2]
```diff
@@ -150,4 +153,11 @@ public void receive(IntegrationError integrationError) {
             managementService.executeCommand(CompositeCommand.of(commands.toArray(Command[]::new)));
         }
     }
+
+    private static List<Command<?>> restoreCommandList(List<Command<?>> commands) {
```
Comment (jesty) [inline activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/channel/ServiceTaskIntegrationErrorEventHandler.java]: can you remove static

**Review by jesty — CHANGES_REQUESTED** [review]

File: activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/channel/ServiceTaskIntegrationErrorEventHandler.java (hunk 2 above)
Comment (mavotto) [reply activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/channel/ServiceTaskIntegrationErrorEventHandler.java]: Done

**Review by jesty — APPROVED** [review]
LGTM
